# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-21 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='users_id_tech',
            field=models.ForeignKey(db_column='users_id_tech', on_delete=django.db.models.deletion.CASCADE, to='clientapp.GLPI_user', verbose_name='\u041e\u0442\u0432\u0435\u0442\u0441\u0442\u0432\u0435\u043d\u043d\u043e\u0435 \u043b\u0438\u0446\u043e'),
        ),
    ]
