# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-22 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0004_glpi_user_auths_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glpi_user',
            name='auths_id',
            field=models.IntegerField(default=0),
        ),
    ]
