# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-22 06:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0005_auto_20170322_0542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('serial', models.CharField(default='\u041d\u0435 \u043d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u043e', max_length=255, verbose_name='\u0421\u0435\u0440\u0438\u044f')),
                ('otherserial', models.CharField(default='\u041d\u0435 \u043d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u043e', max_length=255, verbose_name='\u0418\u043d\u0432\u0435\u043d\u0442\u0430\u0440\u043d\u044b\u0439 \u043d\u043e\u043c\u0435\u0440')),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapp.Location', verbose_name='\u0410\u0443\u0434\u0438\u0442\u043e\u0440\u0438\u044f')),
                ('users_id_tech', models.ForeignKey(db_column='users_id_tech', on_delete=django.db.models.deletion.CASCADE, to='clientapp.GLPI_user', verbose_name='\u041e\u0442\u0432\u0435\u0442\u0441\u0442\u0432\u0435\u043d\u043d\u043e\u0435 \u043b\u0438\u0446\u043e')),
            ],
            options={
                'db_table': 'glpi_monitors',
            },
        ),
    ]
