# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-18 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0006_monitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('level', models.IntegerField()),
                ('entities_id', models.ForeignKey(db_column='entities_id', on_delete=django.db.models.deletion.CASCADE, to='clientapp.Entities', verbose_name='\u0420\u043e\u0434\u0438\u0442\u0435\u043b\u044c')),
            ],
            options={
                'ordering': ['entities_id_id'],
                'db_table': 'glpi_entities',
            },
        ),
        migrations.AlterModelOptions(
            name='computer',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='location',
            name='entities_id',
        ),
        migrations.AddField(
            model_name='computer',
            name='entities',
            field=models.ForeignKey(default='\u041d\u0435 \u043d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u043e', on_delete=django.db.models.deletion.CASCADE, to='clientapp.Entities', verbose_name='\u041f\u043e\u0434\u0440\u0430\u0437\u0434\u0435\u043b\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='location',
            name='entities',
            field=models.ForeignKey(default='\u041d\u0435 \u043d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u043e', on_delete=django.db.models.deletion.CASCADE, to='clientapp.Entities', verbose_name='\u041f\u043e\u0434\u0440\u0430\u0437\u0434\u0435\u043b\u0435\u043d\u0438\u0435'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='entities',
            field=models.ForeignKey(default='\u041d\u0435 \u043d\u0430\u0437\u043d\u0430\u0447\u0435\u043d\u043e', on_delete=django.db.models.deletion.CASCADE, to='clientapp.Entities', verbose_name='\u041f\u043e\u0434\u0440\u0430\u0437\u0434\u0435\u043b\u0435\u043d\u0438\u0435'),
        ),
    ]
