# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-30 03:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0008_auto_20170503_0443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computer',
            options={'ordering': ['name'], 'verbose_name': '\u041a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440', 'verbose_name_plural': '\u041a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440\u044b'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': '\u0410\u0443\u0434\u0438\u0442\u043e\u0440\u0438\u044f', 'verbose_name_plural': '\u0410\u0443\u0434\u0438\u0442\u043e\u0440\u0438\u0438'},
        ),
        migrations.AlterModelOptions(
            name='monitor',
            options={'verbose_name': '\u041c\u043e\u043d\u0438\u0442\u043e\u0440', 'verbose_name_plural': '\u041c\u043e\u043d\u0438\u0442\u043e\u0440\u044b'},
        ),
        migrations.RemoveField(
            model_name='devicenetworkcards',
            name='frequence',
        ),
        migrations.AlterModelTable(
            name='printer',
            table='glpi_printers',
        ),
    ]
