# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-15 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('Attribute_id', models.AutoField(primary_key=True, serialize=False)),
                ('attr_name', models.CharField(max_length=45, verbose_name='\u0410\u0442\u0442\u0440\u0438\u0431\u0443\u0442')),
                ('attr_value', models.CharField(max_length=45, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
            ],
            options={
                'db_table': 'Attribute',
            },
        ),
        migrations.CreateModel(
            name='MO',
            fields=[
                ('MO_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('serial', models.CharField(max_length=20, verbose_name='\u0418\u043d\u0432\u0435\u043d\u0442\u0430\u0440\u043d\u044b\u0439 \u043d\u043e\u043c\u0435\u0440')),
                ('contact', models.CharField(max_length=45, verbose_name='\u041e\u0442\u0432\u0435\u0442\u0441\u0442\u0432\u0435\u043d\u043d\u043e\u0435 \u043b\u0438\u0446\u043e')),
                ('location', models.CharField(max_length=45, verbose_name='\u0410\u0443\u0434\u0438\u0442\u043e\u0440\u0438\u044f')),
                ('mo_type', models.CharField(max_length=45, verbose_name='\u0422\u0438\u043f')),
            ],
            options={
                'db_table': 'MO',
                'verbose_name': '\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u044c\u043d\u044b\u0439 \u043e\u0431\u044a\u0435\u043a\u0442',
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='MO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_service.MO', verbose_name='\u041c\u041e'),
        ),
    ]
