# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-15 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mo',
            options={'verbose_name': '\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u044c\u043d\u044b\u0439 \u043e\u0431\u044a\u0435\u043a\u0442', 'verbose_name_plural': '\u041c\u0430\u0442\u0435\u0440\u0438\u0430\u043b\u044c\u043d\u044b\u0435 \u043e\u0431\u044a\u0435\u043a\u0442\u044b'},
        ),
        migrations.AlterModelTable(
            name='mo',
            table='MObj',
        ),
    ]
