# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-15 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_service', '0002_auto_20170315_0336'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mo',
            table='MO',
        ),
    ]
