# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rest_service', '0002_delete_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_num', models.IntegerField()),
                ('type', models.TextField()),
                ('auditoria', models.TextField()),
                ('Contact', models.TextField()),
            ],
            options={
                'db_table': 'Tables',
            },
        ),
    ]
