# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-21 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_service', '0003_auto_20170315_0347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': '\u0410\u0442\u0442\u0440\u0438\u0431\u0443\u0442', 'verbose_name_plural': '\u0410\u0442\u0442\u0440\u0438\u0431\u0443\u0442\u044b'},
        ),
    ]
