# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_service', '0003_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_name', models.CharField(max_length=45, verbose_name='\u0410\u0442\u0442\u0440\u0438\u0431\u0443\u0442')),
                ('attr_value', models.CharField(max_length=45, verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
            ],
            options={
                'db_table': 'Attribute',
            },
        ),
        migrations.CreateModel(
            name='MO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('serial', models.CharField(max_length=20, verbose_name='\u0418\u043d\u0432\u0435\u043d\u0442\u0430\u0440\u043d\u044b\u0439 \u043d\u043e\u043c\u0435\u0440')),
                ('contact', models.CharField(max_length=45, verbose_name='\u041e\u0442\u0432\u0435\u0442\u0441\u0442\u0432\u0435\u043d\u043d\u043e\u0435 \u043b\u0438\u0446\u043e')),
                ('location', models.CharField(max_length=45, verbose_name='\u0410\u0443\u0434\u0438\u0442\u043e\u0440\u0438\u044f')),
            ],
            options={
                'db_table': 'MO',
            },
        ),
        migrations.DeleteModel(
            name='Tables',
        ),
        migrations.AddField(
            model_name='attribute',
            name='MO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_service.MO', verbose_name='\u041c\u041e'),
        ),
    ]
