# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-03 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_service', '0004_auto_20170321_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='mo',
            name='note',
            field=models.TextField(blank=True, default='', null=True, verbose_name='\u041f\u0440\u0438\u043c\u0435\u0447\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='mo',
            name='location',
            field=models.CharField(blank=True, default='', max_length=45, null=True, verbose_name='\u0410\u0443\u0434\u0438\u0442\u043e\u0440\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='mo',
            name='mo_type',
            field=models.CharField(blank=True, default='', max_length=45, null=True, verbose_name='\u0422\u0438\u043f'),
        ),
    ]
