# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-30 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_service', '0005_auto_20170503_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('specialist_id', models.AutoField(primary_key=True, serialize=False)),
                ('specialist_name', models.CharField(max_length=100, verbose_name='\u0418\u043c\u044f')),
            ],
            options={
                'db_table': 'specialist',
                'verbose_name': '\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u0438\u0441\u0442',
                'verbose_name_plural': '\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u0438\u0441\u0442\u044b',
            },
        ),
        migrations.AddField(
            model_name='mo',
            name='specialist_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_service.Specialist', verbose_name='\u0421\u043f\u0435\u0446\u0438\u0430\u043b\u0438\u0441\u0442'),
        ),
    ]
